name: Deploy to EC2 (Build on EC2)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
           
            echo "---- Pulling latest code ----"

            # Clone or update repo in ~/em_model
            if [ ! -d ~/em_model ]; then
              git clone https://${{ secrets.GH_PAT }}@github.com/uctconsulting12/em_model.git ~/em_model 
            else
              cd ~/em_model
              git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/uctconsulting12/em_model.git
              git pull origin main
            fi

            echo "---- Building Docker image ----"
            cd ~/em_model
            sudo docker build -t em_image .
            echo "--- remove none images ------"
            sudo docker image prune -f

            echo "---- Stopping old container ----"
            sudo docker stop em_container || true
            sudo docker rm em_container || true

            echo "---- Running new container with AWS creds ----"
            sudo docker run -d \
            --name em_container \
            -p 8008:8008 \
            --gpus all \
            -v /home/ubuntu/.aws:/root/.aws \
            --env-file /home/ubuntu/em_model/.env \
            em_image

            echo "Deployment completed. "